### ISSUE TITLE
Avoid space replacement.

### ISSUE THREAD

**Issue by vitaly-t** [Synor/synor#9]
https://github.com/Synor/synor/blob/920bc81155795047be157f2fda320f753cd44e5d/packages/database-mongodb/src/utils/get-config.ts#L40

You no longer need to do such things, if you simply upgrade `connection-string` to the latest, which has it since v4.0.0, see [#38](https://github.com/vitaly-t/connection-string/issues/38).

**Comment by MunifTanjim** [comment]
Thanks @vitaly-t 😃
